### ISSUE TITLE
Is there any option to insert unicode directly rather than a image? (´･_･`)

### ISSUE THREAD

**Issue by daimajia** [one-signal/emoji-picker#1]

**Comment by jasonpang** [comment]
Hey, I've just added this. You can see it on the updated demo page. Basically just add `data-emoji-input="unicode"` to the textarea that needs Unicode input only. I just added it quickly so it's not exactly robust. Would always appreciate any code quality improvements!

**Comment by daimajia** [comment]
Wow, the OneSignal is really useful. 
But it may not work in China, because the GCM and all of the google service are been blocked by the Chinese government.  :cry:

**Comment by jkasten2** [comment]
@daimajia We also support iOS, Windows Phone, and Amazon Kindle devices. However you're correct with GCM in China, it is block so Android and Chrome push notifications will not work.

**Comment by daimajia** [comment]
Any plan to do something? I'm an Android developer, I really want to try to use the OneSignal to my next project. 
I'm able to help you to enter the Chinese market if you want. There are near 60 million smartphone users, it's a really big market.

**Comment by jkasten2** [comment]
@daimajia We have only briefly looked into ways of support Android users in China. Is [Baidu's Cloud Push ](http://developer.baidu.com/wiki/index.php?title=docs/cplat/push) available to most Chinese devices?

Thanks.

**Comment by daimajia** [comment]
@jkasten2  There are more than 10 companies focusing on  push service. Baidu is just one of them.

- Jpush https://www.jpush.cn/
- GeTui http://www.getui.com/
- XiaoMi http://dev.xiaomi.com/doc/?page_id=1670
- Tencent http://xg.qq.com/ 
- YunBa http://yunba.io/products/push/
- LeanCloud https://leancloud.cn/features/message.html

Most of them at least have own over several million end-users. Some of own billion end-users. But they are all different from you. All the push service company in China only support Android and iOS, and guarantee the push speed only in China. If the developers want to make a global application, they are useless, because they are very slow in foreign country. If the developer Choose the GCM, it will mean that he will give up the Chinese market.  At the same time, some of the US startup wants to enter the Chinese market, they may have no experience on localization. Entering the Chinese market is not means just translate the language. The Google services are been blocked, the Google map also not work at all, of course the push service.

Suppose they know that, they don't know which service they should choose. After they decide, they have to make two version apps for Chinese market and other market.  As you see, all the push service in China are using the Chinese, it's very unfriendly for the foreign developers. 

I think the chance for you is here, making a push service which can be easily integrated, support both Chinese market and global market.  

An example I know is the [CloudMagic](https://cloudmagic.com/) which is an popular Email app. They choose GCM as push service, they may never realize that their push service can not work  at all in China.

**Comment by jkasten2** [comment]
@daimajia Wow thanks for the very detailed information!

I've heard of Baidu being referred to as 'the Google of China' and was hoping their device messaging (GCM equivalent {Cloud Push }) was installed on most Android devices out of the box. Do you know where I could find updated numbers on the active install base on these providers? Implementing all of them would not be feasible but the top few is something we could consider.

Thanks.

**Comment by daimajia** [comment]
Check this link  http://www.csdn.net/article/a/2011-06-02/299188 .
It's published at 05 2014, it said that the Baidu Cloud Push daily active user has over 200 million.
