### ISSUE TITLE
Does not show in Iphone Safair

### ISSUE THREAD

**Issue by mymjack** [one-signal/emoji-picker#16]
First thank you for this nice work. I know it is a lot of effort.
So I did all steps you showed and its not appearing on iphones. It works on PC and Android though.  Here are some minor bugs. On small screens the emoji drawer could be out of the screen. On android it sometimes flies to the left.

**Comment by gdeglin** [comment]
The lack of iPhone support is intentional -- iOS already has a built-in emoji keyboard that is compatible. The same is true for Android devices in most cases so you may want to just disable the emoji picker on mobile devices.
