### ISSUE TITLE
Why render emoji as images at all?

### ISSUE THREAD

**Issue by eremzeit** [one-signal/emoji-picker#18]
Maybe I'm a noob but I don't understand why you chose to render the emojis in the picker via an image rather than rendering as unicode.  Browsers support rendering emojis as unicode.  Unless you want to force a specific emoji image set (eg. google, twitter, or apple) requiring the user to download a spritesheet seems to me like a waste of bandwidth.  Am I misunderstanding something with how emojis work?

**Comment by gdeglin** [comment]
Many browsers and devices don't support rendering emoji, such as Chrome on Android 4.3 and below, Chrome on OS X 10.9 and below, or Chrome on any version of Windows.

**Comment by eremzeit** [comment]
Ah, I've been researching more and found this to be correct.

More info:
http://blog.getemoji.com/post/57054354336/which-browsers-support-emoji

**Comment by patrick-mcdougle** [comment]
Rendering them as images might have copyright issues see #123
