### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [one-signal/emoji-picker#2]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5570

**Comment by sklintch** [comment]
I believe it is here: https://github.com/wedgies/jquery-emoji-picker/blob/master/package.json

**Comment by gdeglin** [comment]
Thanks for filing the issue @maruilian11. @jasonpang, could you look into this when you have a free moment?

**Comment by gdeglin** [comment]
Done. @maruilian11 could you confirm that I did it right? Thanks!

**Comment by maruilian11** [comment]
@gdeglin could you change the repo url to https://github.com/one-signal/emoji-picker?
btw, i think you did it very well :)

**Comment by gdeglin** [comment]
Sure thing. I just updated it (https://github.com/one-signal/emoji-picker/commit/1bca85052ce804ee6649adb99b5905059e50c42e).
