### ISSUE TITLE
Emoji Picker Icon Not Showing

### ISSUE THREAD

**Issue by mjp1** [one-signal/emoji-picker#28]
Looks like it's taking over my input box correctly, however, the actual emoji picker icon isn't showing. I have font-awesome correctly inserted into my <head> tag. 

Here is what the <i> tag looks like
`<i class="emoji-picker-icon emoji-picker undefined" data-id="b7aa839f-a6fa-4354-8a33-cfcadf8cba1a" data-type="picker"></i>`

**Comment by Nawako** [comment]
How di you solve your issue ? I have currently the same problem.

**Comment by jaxn** [comment]
@Nawako, not sure if you figured it out, but I am dealing with this right now too.

In my situation, I am trying to use emoji-picker in a modal.  The `undefined` should be `fa fa-smile-o`, but I haven't figured out why it is happening yet.

**Comment by Nawako** [comment]
I dealt with it by placing <script>Jquery</script> on top of the file.

Date: Wed, 5 Oct 2016 13:11:17 -0700
